'use strict';

module.exports = [
	//NB: the outermost item to be arrayified must come first
	'artists.artist',
	'chart.chartItem',
	'chart.chartItem.release.download.packages.package',
	'chart.chartItem.release.download.packages.package.formats.format',
	'chart.chartItem.track.download.packages.package',
	'chart.chartItem.track.download.packages.package.formats.format',
	'releases.release',
	'releases.release.download.packages.package',
	'releases.release.download.packages.package.formats.format',
	'searchResults.searchResult',
	'searchResults.searchResult.release.download.packages.package',
	'searchResults.searchResult.release.download.packages.package.formats.format',
	'searchResults.searchResult.track.download.packages.package',
	'searchResults.searchResult.track.download.packages.package.formats.format',
	'recommendations.recommendedItem',
	'recommendations.recommendedItem.release.download.packages.package',
	'recommendations.recommendedItem.release.download.packages.package.formats.format',
	'tags.tag',
	'tracks.track',
	'tracks.track.download.packages.package',
	'tracks.track.download.packages.package.formats.format',
	'track.download.packages.package',
	'track.download.packages.package.formats.format',
	'taggedResults.taggedItem',
	'taggedResults.taggedItem.release.download.packages.package',
	'taggedResults.taggedItem.release.download.packages.package.formats.format',
	'cardTypes.cardType',
	'locker.lockerReleases.lockerRelease',
	'locker.lockerReleases.lockerRelease.lockerTracks.lockerTrack',
	'locker.lockerReleases.lockerRelease.lockerTracks.lockerTrack.downloadUrls.downloadUrl',
	'release.formats.format',
	'release.download.packages.package',
	'release.download.packages.package.formats.format',
	'list.listItems.listItem',
	'list.listItems.listItem.release.download.packages.package',
	'list.listItems.listItem.release.download.packages.package.formats.format',
	'basket.basketItems.basketItem',
	'cards.card',
];
